name: Build Python Package

on:
  push:

permissions:
  contents: read

jobs:

  build-sirabus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/build
      with:
        release-tag: 0.0.0
